# Generated by Django 4.0 on 2025-02-21 03:37

from django.db import migrations, models
import django.db.models.deletion
import musicapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(default='No bio available')),
                ('profile_image', models.ImageField(default='path/to/default/profile_image.jpg', upload_to='artists/profile_images/')),
                ('background_image', models.ImageField(default='path/to/default/background_image.jpg', upload_to='artists/background_images/')),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(verbose_name='ユーザID')),
                ('user_name', models.CharField(max_length=25, verbose_name='ユーザ名')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(default='songs/default_song.mp3', upload_to=musicapp.models.user_path, verbose_name='曲ファイル')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicapp.artist')),
            ],
        ),
    ]
